# Generated by Django 4.2.16 on 2024-09-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('category', models.CharField(max_length=10)),
                ('phoneNum', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=450)),
                ('password', models.CharField(max_length=50)),
                ('unique_id', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
    ]
