# Generated by Django 4.2.16 on 2024-09-26 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_alter_institute_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institute',
            name='address',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='category',
        ),
        migrations.RemoveField(
            model_name='institute',
            name='phoneNum',
        ),
    ]
