# Generated by Django 4.2.16 on 2024-09-26 09:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='createdby',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
